version: 2
jobs:
    build-and-push:
        docker:
            -   image: cimg/base:current
                environment:
                    IMAGE_NAME: fullfrontend/php-fpm
        steps:
            - checkout
            - setup_remote_docker

            - run:
                    name: "Build and push Docker image"
                    command: |
                        docker build -t ${IMAGE_NAME}:8.0 -f 8.0/Dockerfile .
                        docker build -t ${IMAGE_NAME}:8.1 -f 8.1/Dockerfile .
                        docker build -t ${IMAGE_NAME}:8.2 -f 8.2/Dockerfile .
                        docker build -t ${IMAGE_NAME}:8.3 -f 8.3/Dockerfile .
                        docker build -t ${IMAGE_NAME}:8.4 -f 8.4/Dockerfile .
                        docker tag ${IMAGE_NAME}:8.4 ${IMAGE_NAME}:latest
                        
                        echo ${FFE_DOCKER_PWD} | docker login -u ${FFE_DOCKER_LOGIN} --password-stdin
                        docker push --all-tags ${IMAGE_NAME}

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build-and-push:
                context: 'Docker Hub'
                filters:
                    branches:
                        only: master


