version: 2
jobs:
    build-and-push:
        docker:
            -   image: cimg/base:current
                environment:
                    IMAGE_NAME: he8us/php-fpm
        steps:
            - checkout
            -   setup_remote_docker:
                    version: 20.10.6

            -   run:
                    name: "Build and push Docker image"
                    command: |
                        docker build -t ${IMAGE_NAME}:8.0 -f 8.0/Dockerfile .
                        docker build -t ${IMAGE_NAME}:8.1 -f 8.1/Dockerfile .
                        docker build -t ${IMAGE_NAME}:8.2 -f 8.2/Dockerfile .
                        docker tag ${IMAGE_NAME}:8.2 ${IMAGE_NAME}:latest
                        
                        echo ${DOCKER_PWD} | docker login -u ${DOCKER_LOGIN} --password-stdin
                        docker push --all-tags ${IMAGE_NAME}

workflows:
    version: 2
    build-and-deploy:
        jobs:
            - build-and-push:
                context: 'Docker Hub'
                filters:
                    branches:
                        only: master


